# TERMINAL COLORS
# https://github.com/BlueArduino20/terminal-colors
NO_COLOR="\e[0m"
WHITE="\e[0;17m"
BOLD_WHITE="\e[1;37m"
BLACK="\e[0;30m"
BLUE="\e[0;34m"
BOLD_BLUE="\e[1;34m"
GREEN="\e[0;32m"
BOLD_GREEN="\e[1;32m"
CYAN="\e[0;36m"
BOLD_CYAN="\e[1;36m"
RED="\e[0;31m"
BOLD_RED="\e[1;31m"
PURPLE="\e[0;35m"
BOLD_PURPLE="\e[1;35m"
BROWN="\e[0;33m"
BOLD_YELLOW="\e[1;33m"
GRAY="\e[0;37m"
BOLD_GRAY="\e[1;30m"
# END OF TERMINAL COLORS

echo -e "${NO_COLOR}NO_COLOR"
echo -e "${WHITE}WHITE"
echo -e "${BOLD_WHITE}BOLD_WHITE"
echo -e "${BLACK}BLACK"
echo -e "${BLUE}BLUE"
echo -e "${BOLD_BLUE}BOLD_BLUE"
echo -e "${GREEN}GREEN"
echo -e "${BOLD_GREEN}BOLD_GREEN"
echo -e "${CYAN}CYAN"
echo -e "${BOLD_CYAN}BOLD_CYAN"
echo -e "${RED}RED"
echo -e "${BOLD_RED}BOLD_RED"
echo -e "${PURPLE}PURPLE"
echo -e "${BOLD_PURPLE}BOLD_PURPLE"
echo -e "${BROWN}BROWN"
echo -e "${BOLD_YELLOW}BOLD_YELLOW"
echo -e "${GRAY}GRAY"
echo -e "${BOLD_GRAY}BOLD_GRAY"
